### ISSUE TITLE
Compiling error in SWXSLTransform with iOS 7 SDK or 10.9 (Xcode 5)

### ISSUE THREAD

**Issue by RobertCain** [oriontransfer/SWXMLMapping#1]
When using iOS 7 or 10.9 SDK SWXSLTransform.m will not compile without a small change. I have discovered that due to changes in libxml, it needed changing to use the new output buffer accessor methods for the xmloutput buffer

Line 98 causes error 'Incomplete definition of type struct_xmlBuf'
`NSData * result = [[[NSData alloc] initWithBytes:outputBuffer->buffer->content length:outputBuffer->buffer->use] autorelease];`

With the new accessor method this becomes
`NSData * result = [[NSData alloc] initWithBytes:xmlOutputBufferGetContent(outputBuffer) length:xmlOutputBufferGetSize(outputBuffer)];`

This works fine but when run on iOS 6 it not surprisingly results in 'symbol not found'. I can't seem to work out how to do it conditionally in a way which Xcode will compile with base SDK iOS 7 and run on both iOS 6 and iOS 7.

I have been trying and considering:
- Checking xmlOutputBufferGetContent != NULL
- Using libxml2.2 instead of libxml2
- Checking LIBXML_DOTTED_VERSION
- Checking for LIBXML2_NEW_BUFFER new methods defined

But all of these result in only one line always being chosen before or after compilation. The few other people dealing with this issue (Googling) appear to be always compiling targeting one version of libxml.

**Comment by RobertCain** [comment]
Solution to the above and discussion at http://stackoverflow.com/questions/18893959/conditionally-compiling-for-differences-in-libxml2-in-ios-7/

**Comment by ioquatix** [comment]
Ah, awesome, sorry I missed this! Do you want to submit a PR?

**Comment by ioquatix** [comment]
Actually, I just checked and it looks like I fixed this a while ago:

https://github.com/oriontransfer/SWXMLMapping/blob/128821a346077f37cf76de05f94d2d07b091b78c/SWXSLTransform.m#L93-L94

**Comment by ioquatix** [comment]
Sorry about how long it took to reply! I didn't see the original notification for some reason.
